CREATE TABLE IF NOT EXISTS AccountSecurity (
    AccountType VARCHAR(20) NOT NULL,
    UserId VARCHAR(120) NOT NULL,
    DisplayName VARCHAR(160) NULL,
    AvatarDataUrl TEXT NULL,
    TotpSecretEncrypted TEXT NULL,
    TotpEnabled BOOLEAN NOT NULL DEFAULT FALSE,
    PendingTotpSecretEncrypted TEXT NULL,
    PendingTotpExpiresAt TIMESTAMPTZ NULL,
    RecoveryCodeHashes JSONB NOT NULL DEFAULT '[]'::jsonb,
    RecoveryCodeSalt VARCHAR(80) NULL,
    LoginAlertEnabled BOOLEAN NOT NULL DEFAULT TRUE,
    IdleTimeoutMinutes INTEGER NOT NULL DEFAULT 20160,
    DeleteRequestedAt TIMESTAMPTZ NULL,
    DeleteRequestStatus VARCHAR(30) NULL,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AccountType, UserId)
);

ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS DisplayName VARCHAR(160) NULL;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS AvatarDataUrl TEXT NULL;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS TotpSecretEncrypted TEXT NULL;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS TotpEnabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS PendingTotpSecretEncrypted TEXT NULL;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS PendingTotpExpiresAt TIMESTAMPTZ NULL;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS RecoveryCodeHashes JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS RecoveryCodeSalt VARCHAR(80) NULL;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS LoginAlertEnabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS IdleTimeoutMinutes INTEGER NOT NULL DEFAULT 20160;
ALTER TABLE AccountSecurity ALTER COLUMN IdleTimeoutMinutes SET DEFAULT 20160;
UPDATE AccountSecurity SET IdleTimeoutMinutes = 20160 WHERE IdleTimeoutMinutes <> 20160;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS DeleteRequestedAt TIMESTAMPTZ NULL;
ALTER TABLE AccountSecurity ADD COLUMN IF NOT EXISTS DeleteRequestStatus VARCHAR(30) NULL;

CREATE TABLE IF NOT EXISTS SecurityEvents (
    Id BIGSERIAL PRIMARY KEY,
    AccountType VARCHAR(20) NOT NULL,
    UserId VARCHAR(120) NOT NULL,
    EventType VARCHAR(60) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'success',
    Detail TEXT NULL,
    IpPrefix VARCHAR(80) NULL,
    DeviceLabel VARCHAR(220) NULL,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_securityevents_account_created
    ON SecurityEvents (AccountType, UserId, CreatedAt DESC);

CREATE TABLE IF NOT EXISTS TrustedDevices (
    AccountType VARCHAR(20) NOT NULL,
    UserId VARCHAR(120) NOT NULL,
    DeviceHash CHAR(64) NOT NULL,
    DeviceType VARCHAR(60) NULL,
    Browser VARCHAR(100) NULL,
    Platform VARCHAR(100) NULL,
    IpPrefix VARCHAR(80) NULL,
    FirstSeenAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastSeenAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AccountType, UserId, DeviceHash)
);

CREATE TABLE IF NOT EXISTS AuthSessions (
    SessionHash CHAR(64) PRIMARY KEY,
    SessionId VARCHAR(50) NULL,
    UserId VARCHAR(120) NOT NULL,
    AccountType VARCHAR(20) NOT NULL,
    Role VARCHAR(20) NOT NULL,
    AssignedTeacherId VARCHAR(120) NULL,
    ActorUserId VARCHAR(120) NULL,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastSeenAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ExpiresAt TIMESTAMPTZ NOT NULL
);

ALTER TABLE AuthSessions ADD COLUMN IF NOT EXISTS SessionId VARCHAR(50) NULL;
ALTER TABLE AuthSessions ADD COLUMN IF NOT EXISTS DeviceHash CHAR(64) NULL;
ALTER TABLE AuthSessions ADD COLUMN IF NOT EXISTS DeviceType VARCHAR(60) NULL;
ALTER TABLE AuthSessions ADD COLUMN IF NOT EXISTS Browser VARCHAR(100) NULL;
ALTER TABLE AuthSessions ADD COLUMN IF NOT EXISTS Platform VARCHAR(100) NULL;
ALTER TABLE AuthSessions ADD COLUMN IF NOT EXISTS IpPrefix VARCHAR(80) NULL;
ALTER TABLE AuthSessions ADD COLUMN IF NOT EXISTS UserAgent VARCHAR(500) NULL;
ALTER TABLE AuthSessions ADD COLUMN IF NOT EXISTS IdleTimeoutMinutes INTEGER NOT NULL DEFAULT 20160;
ALTER TABLE AuthSessions ALTER COLUMN IdleTimeoutMinutes SET DEFAULT 20160;
UPDATE AuthSessions
SET IdleTimeoutMinutes = 20160,
    ExpiresAt = GREATEST(ExpiresAt, LastSeenAt + INTERVAL '14 days')
WHERE IdleTimeoutMinutes <> 20160 OR ExpiresAt < LastSeenAt + INTERVAL '14 days';
UPDATE AuthSessions
SET SessionId = 'legacy_' || SUBSTRING(SessionHash, 1, 32)
WHERE SessionId IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_authsessions_public_id ON AuthSessions (SessionId);
CREATE INDEX IF NOT EXISTS idx_authsessions_account_last_seen
    ON AuthSessions (AccountType, UserId, LastSeenAt DESC);
